server:
  port: 8761    #DEFAULT_URL = "http://localhost:8761" #
spring:
  application:
    name: eureka-server
eureka:
  #client:
    #是否将自己注册到Eureka Server上，默认为true
    #register-with-eureka: false
    #是否从Eureka Server上获取注册信息，默认为true
    #fetch-registry: false
