server:
  port: 8011    #DEFAULT_URL = "http://localhost:8761" #
spring:
  application:
    name: eureka-server-ming
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8011/eureka, http://127.0.0.1:8012/eureka

  #client:
    #是否将自己注册到Eureka Server上，默认为true
    #register-with-eureka: false
    #是否从Eureka Server上获取注册信息，默认为true
    #fetch-registry: false
